- name: Create a directory if it does not exist
  ansible.builtin.file:
    path: /home/pi/scripts
    state: directory
    mode: 0755
    owner: pi 
    group: pi

- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - python3-pip
    - mc
    - nano
    - htop

- name: Create cron task
  ansible.builtin.cron:
    name: "backup thunderbird"
    weekday: "2"
    minute: "0"
    hour: "0"
    user: pi
    job: "cd /home/pi/docker/duplicati/source && sudo tar -zcvf thunderbird_profile_rasp.tar.gz /home/pi/docker/thunderbird/ > /dev/null 2>&1" 

