- name: Install a list of packages
  ansible.builtin.apt:
    pkg:
    - python3-pip
    - mc
    - nano
    - htop
    - ansible

- name: Install pexpect using Pip.
  pip:
    name: pexpect 
    state: present
    executable: "{{ pip_executable }}"


